### PR TITLE
fix: set min-width of DateRangeInput resolve infinite update

### LINKED ISSUE #1162: Activity Report Edit Page Bug
# 이슈 내용 \*

Date Range Input position & shape mismatching the design
Malfunctioning input for most text inputs

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

### PR DESCRIPTION
**Pull request by Davidace136**
# 요약 \*

set min-width of DateRangeInput to 300px and resolve infinite update bug of date input in ActivityReportEditFrame

It closes #1162

# 스크린샷

스크린샷 2024-10-09 오후 11 09 44

# 이후 Task \*

- 없음

### CODE REVIEW

File: packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx [hunk 1]
```diff
@@ -60,11 +60,13 @@ const InputFrameInner = styled.div`
 `;
 
 const DescriptionInputFrameInner = styled.div`
-  width: 100%;
+  /* width: 100%; */
```
Comment (babycroc) [inline packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx:63]: 이 줄 주석 걸거면 지워주세용

**Review by babycroc — APPROVED** [review]
